<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Barbershop App Demo Website">
<meta name="author" content="Arturo Hernández">
    
theme: jekyll-theme-midnight
